services:
  - type: web
    name: cluster
    branch: master
    plan: free
    dockerfilePath: ./Dockerfile
    repo: https://github.com/Nrgodara/TeraBoxDL
    env: docker
    envVars:
      - key: CLUSTER_01
        sync: false
    autoDeploy: false
